### ISSUE TITLE
Build fails after fresh install

### ISSUE THREAD

**Issue by emassey2** [ropod-project/tree-ropod#13]
After installing ros-kinetic on a fresh ubuntu 16.04 machine, I ran the install script from my home directory. The catkin build appears to be failing. It appears to have to do with no finding the CMakeLists.txt file in /opt/ropod/ropod_common/ropodcpp/ftsm. There is a example CMakeLists.txt file, which if you copy and run the build again you'll still get an error. This leads me to believe something bigger is going on. I've attached the terminal output.

``
[install_output.txt](https://github.com/ropod-project/tree-ropod/files/3382848/install_output.txt)

**Comment by alex-mitrevski** [comment]
The problem has to be that the `ropod_common` copy on GitHub, which is cloned by the install script, hasn't been updated in quite a while. As a temporary fix, please reclone `ropod_common` (on the `develop` branch) from the ROPOD git server.

**Comment by argenos** [comment]
@alex-mitrevski I guess maybe it makes sense to update the script to clone from gitlab instead (since it's always up to date). 

@emassey2 if that happens to fix your problem, would you mind opening a PR with the right remote?

**Comment by argenos** [comment]
Solved in #14
