### ISSUE TITLE
Add new repos to rosinstall file

### ISSUE THREAD

**Issue by DharminB** [ropod-project/tree-ropod#16]
Add following repos to `.rosinstall` file
- `elevator_navigation`
- `cart_collection/cart_detection`
- `ed_entity_server`

**Comment by alex-mitrevski** [comment]
The components for cart collection/cart detection and the ED entity server have to be added as well.

**Comment by alex-mitrevski** [comment]
Resolved by https://github.com/ropod-project/tree-ropod/pull/17
